### ISSUE TITLE
The command "python setup.py test" exited with 1

### ISSUE THREAD

**Issue by saeedsq** [saeedsq/django-fancy-cronfield#3]
```
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    test_suite='runtests.main',
  File "/opt/python/2.7.9/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/python/2.7.9/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/python/2.7.9/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/setuptools/command/test.py", line 121, in with_project_on_sys_path
    require('%s==%s' % (ei_cmd.egg_name, ei_cmd.egg_version))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 1.5.12 (/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages), Requirement.parse('django==1.5'), set(['django-fancy-cronfield']))
```

**Comment by saeedsq** [comment]
The command "python setup.py test" exited with 0.
Done. Your build exited with 1.

**Comment by saeedsq** [comment]
The real cause is this:

```
$ pep8 fancy_cronfield
fancy_cronfield/validators.py:19:80: E501 line too long (133 > 79 characters)
fancy_cronfield/tests/test_validators.py:91:80: E501 line too long (85 > 79 characters)
```
